#### Load modules

In [1]:
import pandas as pd
import sys, os
from gpt4all import GPT4All
from tqdm import tqdm
import re
from deep_translator import GoogleTranslator

sys.path.append("\\".join(os.getcwd().split("\\")[:-1]))
%load_ext autoreload
%autoreload 2
from utils import *
from scraper import utils
from scraper.workflow.hashing.hashing_method import normalize_then_hash

C:\Users\ma1021525\AppData\Roaming\Python\Python39\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
<frozen importlib._bootstrap>:228: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute
<frozen importlib._bootstrap>:228: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute

#### Import data and language model

In [2]:
data = pd.read_pickle(os.path.join("/".join(os.getcwd().split("\\")[:-1]),
                                   'scraper','data/merged_data.pkl'))
# define the language model (Llama with 8 billion parameters is about 4.66 GB)
model = GPT4All('Meta-Llama-3-8B-Instruct.Q4_0.gguf')

In [3]:
print(data.loc[data['title'].str.contains('Feuerwehrplan')]['title_it'].to_markdown())

|       | title_it                       |
|------:|:-------------------------------|
| 19113 | Piano dei vigili del fuoco Gde |
| 19349 | Piano dei vigili del fuoco Gde |
| 38798 | Piano dei vigili del fuoco Gde |
| 38965 | Piano dei vigili del fuoco Gde |

#### Clean the input database

In [ ]:
language_dict = {'english':('EN', 'ENG'), 'french':('FR','FRA'), 'german':('DE','DEU'), 'italian':('IT','ITA'), 'not_found':('NA','NAN')}
data['lang_3'] = data.apply(lambda row: language_dict[utils.detect_language(row['abstract'], not_found=True)][1], axis=1)
data['lang_2'] = data.apply(lambda row: language_dict[utils.detect_language(row['abstract'], not_found=True)][0], axis=1)
# for idx, row in data.iterrows():
#     if row['abstract'] != 'nan':
#         if language_dict[detect_language(row['abstract_it'])][1] != 'ITA':
#             trnd = GoogleTranslator(source='auto', target='ita').translate(row['abstract'])
#             data.loc[idx, 'abstract_it'] = trnd
#         if language_dict[detect_language(row['abstract_de'])][1] != 'DEU':
#             trnd = GoogleTranslator(source='auto', target='de').translate(row['abstract'])
#             data.loc[idx, 'abstract_de'] = trnd
#         if language_dict[detect_language(row['abstract_fr'])][1] != 'FRA':
#             trnd = GoogleTranslator(source='auto', target='fr').translate(row['abstract'])
#             data.loc[idx, 'abstract_fr'] = trnd
#         if language_dict[detect_language(row['abstract_en'])][1] != 'ENG':
#             trnd = GoogleTranslator(source='auto', target='en').translate(row['abstract'])
#             data.loc[idx, 'abstract_en'] = trnd

#### Extract keywords with a local Llama model

In [13]:
data['abstract_w_count'] = data.apply(lambda x: len(x['abstract'].split(' ')), axis=1)
data.apply(lambda x: 'nan' if x['abstract'].startswith(('??','Es werden die Daten im Zeitraum','Link zu Metadaten:',
                                                'https:',
                                                'geo@bs.ch',
                                                'info.geoportal@be.ch',
                                                'sit@jura.ch',
                                                'geodaten@sg.ch',
                                                'info@example.com',
                                                'agi@tg.ch',
                                                'mail@lisag.ch',
                                                'gis@bd.zh.ch',
                                                'info.diffusion@vd.ch',
                                                'webgis@swisstopo.ch'))
                                                else x['abstract'], axis=1)
len(data[(data['abstract'] != 'nan') &
     (data['abstract'] != data['title']) &
     (data['abstract_w_count']>4)])

c:\Users\ma1021525\Anaconda3\envs\geoharvester\lib\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
c:\Users\ma1021525\Anaconda3\envs\geoharvester\lib\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
c:\Users\ma1021525\Anaconda3\envs\geoharvester\lib\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
c:\Users\ma1021525\Anaconda3\envs\geoharvester\lib\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

5939

In [15]:
# iterate through the dataframe
task = "Extract a list of key words comma separated without adjectives in original language from the following text: "
en_trns_task = "Translate the following list of words into a comma separated list in English: "
de_trns_task = "Übersetze die folgende Liste von Wörtern in eine durch Komma getrennte Liste auf Deutsch: "
fr_trns_task = "Traduisez la liste de mots suivante en une liste séparée par des virgules en francais: "
it_trns_task = "Traduci il seguente elenco di parole in un elenco separato da virgole in italiano: "

df_kg = pd.DataFrame()

for idx, row in tqdm(data.iterrows()):
    if idx > 100:
        continue
    trns_dict = {"ENG":en_trns_task, "DEU":de_trns_task, "ITA":it_trns_task,'FRA':fr_trns_task}
    if row['lang_3'] != 'NAN':
        del trns_dict[row['lang_3']]
    # filter rows with no abstract and use title instead
    if row['abstract'] == 'nan' or row['abstract']==row['title'] or len(row['abstract'].split(' '))<5 or row['abstract'].startswith(('??',
                                                                                                                                      'Es werden die Daten im Zeitraum',
                                                                                                                                      'Link zu Metadaten:',
                                                                                                                                      'https:',
                                                                                                                                      'geo@bs.ch',
                                                                                                                                      'info.geoportal@be.ch',
                                                                                                                                      'sit@jura.ch',
                                                                                                                                      'geodaten@sg.ch',
                                                                                                                                      'info@example.com',
                                                                                                                                      'agi@tg.ch',
                                                                                                                                      'mail@lisag.ch',
                                                                                                                                      'gis@bd.zh.ch',
                                                                                                                                      'info.diffusion@vd.ch',
                                                                                                                                      'webgis@swisstopo.ch')):
        # llama_answer = ask_llama(task, row['title'], idx)
        pass
    else:
        # generate LLM response with abstract and interpret it
        kwds = read_keyowrds(ask_llama(task, row['abstract']))

        df_kg = collect_keywords(kwds, row['lang_3'], trns_dict, df_kg)
        # for lang in [k for k in trns_dict.keys()]:
        #     llama_translation = ask_llama(trns_dict[lang], ", ".join(kwds), idx, check_response=False)
        #     translations[lang] = read_translation(llama_translation)
        # if check_length(translations, len(kwds)):
        #     df = pd.DataFrame({row['lang_3']:kwds})
        #     for lang in [k for k in trns_dict.keys()]:
        #         df[lang] = translations[lang]
        #         # data.loc[idx, 'kg_'+lang] = ','.join(translations[lang])
        #     # data.loc[idx, 'kg_'+row['lang_3']] = ','.join(kwds)
        #     df_kg = pd.concat([df_kg, df], axis=0, ignore_index=True)
        # else:
        #     print("Differing translation lengths!")

remove_rows = df_kg.applymap(lambda x: len(x.split(" "))).apply(sum, axis=1).loc[lambda x:x==4].index.tolist()
df_kg.drop(remove_rows, inplace=True)

0it [00:00, ?it/s]c:\Users\ma1021525\Anaconda3\envs\geoharvester\lib\site-packages\pandas\core\dtypes\cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
2it [03:39, 111.17s/it]

Skipping differing translation lengths!

61it [1:12:09, 45.98s/it]

Skipping differing translation lengths!

75it [1:25:45, 56.59s/it]

Skipping differing translation lengths!

76it [1:27:11, 65.39s/it]

Skipping differing translation lengths!

78it [1:30:14, 77.17s/it]

Skipping differing translation lengths!

81it [1:33:18, 68.36s/it]

Skipping differing translation lengths!

83it [1:37:02, 92.51s/it]

Skipping differing translation lengths!

84it [1:39:17, 105.34s/it]

Skipping differing translation lengths!

87it [1:42:45, 84.20s/it]

Skipping differing translation lengths!

88it [1:44:24, 88.48s/it]

Skipping differing translation lengths!

39395it [1:57:41,  5.58it/s]

#### Clean the resulting dataframe

In [3]:
df_kg = pd.read_pickle('kg_data.pkl')
df_kg = filter_translations(df_kg)
for i, row in df_kg.iterrows():
    if len(row['ITA'].split()) < 2 and len(row['DEU'].split())<2 and len(row['ENG'].split())<2 and len(row['FRA'].split())<2:
        df_kg.drop(i, inplace=True)
df_kg.drop(columns=['NAN'], inplace=True)
df_kg['ITA'] = df_kg['ITA'].str.replace('.', '')
df_kg['DEU'] = df_kg['DEU'].str.replace('.', '')
df_kg['ENG'] = df_kg['ENG'].str.replace('.', '')
df_kg['FRA'] = df_kg['FRA'].str.replace('.', '')
to_drop = [2,12,16,21,20,23,24,30,37,44]
df_kg.drop(to_drop, inplace=True)
df_kg = df_kg.reset_index(drop=True)


to_drop = [5,6,19,5,5,90,91,178,173,110, 180, 202, 285, 382, 456,196, 299, 842]
to_drop.extend([k for k in range(8, 12)])
# to_drop.extend([k for k in range(8, 12)])
df_kg.drop(to_drop, inplace=True)

C:\Users\ma1021525\AppData\Local\Temp\ipykernel_23012\1071384662.py:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_kg['ITA'] = df_kg['ITA'].str.replace('.', '')
C:\Users\ma1021525\AppData\Local\Temp\ipykernel_23012\1071384662.py:8: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_kg['DEU'] = df_kg['DEU'].str.replace('.', '')
C:\Users\ma1021525\AppData\Local\Temp\ipykernel_23012\1071384662.py:9: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_kg['ENG'] = df_kg['ENG'].str.replace('.', '')
C:\Users\ma1021525\AppData\Local\Temp\ipykernel_23012\1071384662.py:10: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_kg['FRA'] = df_kg['FRA'].str.replace('.', '')

In [74]:
search = 'Wohnungsinventar'
col = 'title'
print(data.loc[data['title'].str.contains(search)][[col+'_de',col+'_en',col+'_it',col+'_fr']].to_markdown())

|       | title_de         | title_en          | title_it                    | title_fr                 |
|------:|:-----------------|:------------------|:----------------------------|:-------------------------|
| 19915 | Wohnungsinventar | Housing inventory | Inventario delle abitazioni | Inventaire des logements |
| 21218 | Wohnungsinventar | Housing inventory | Inventario delle abitazioni | Inventaire des logements |
| 38593 | Wohnungsinventar | Housing inventory | Inventario delle abitazioni | Inventaire des logements |

In [54]:
df_kg[df_kg['DEU'] =='Gefahrenkarte']['ITA'].unique()

array(['Carta dei pericoli', 'Carta di pericolo', 'Mappa dei pericoli',
       'Carta di pericoli', 'Grafico di pericoli'], dtype=object)

In [32]:
df_kg = pd.read_csv('kg_data.csv', delimiter=';', low_memory=False, header=0)

In [33]:
df_kg.drop(columns=['ENG_cap','ITA_cap','FRA_cap'], inplace=True)
df_kg.head()

,DEU,ENG,ITA,FRA
0,Alpkataster,alpine catalogue,catasto alpino,catalogue des alpages
1,Amphibienvorkommen,amphibian occurrences,presenza di anfibi,présence d amphibiens
2,Stand,stand,punto vendita,stand
3,Landeskarten,national maps,cartine territoriali,cartes régionales
4,Übersichtsplan,overview plan,piano di insieme,plan d ensemble

In [16]:
df_kg.to_pickle('kg_data_cleaned.pkl')

In [14]:
df_kg.loc[df_kg['DEU'] == 'Brandmeldeanlagen']

,DEU,ENG,ITA,FRA
87,Brandmeldeanlagen,fire alarm systems,sistemi di allarme antincendio,systèmes d alarme incendie

#### Generate the knowledge graph

In [28]:
df_kg = pd.read_pickle('kg_data.pkl')
# for i, row in df_kg.iterrows():
#     if len(row['ITA']) < 5 or len(row['DEU'])<5 or len(row['ENG'])<5 or len(row['FRA'])<5:
#         df_kg.drop(i, inplace=True)

In [9]:
kg = generate_knowledge_graph("GeoHarvester",'kg_data.pkl', 'knowledge_graph', load_synonyms=True)

KG: Filtering translations...
KG: Loading data in the knowledge graph...
KG: Building synonyms...

In [7]:
lang_terms = find_nodes_by_language(kg, 'italian')
[t for t in lang_terms if t in 'sistemi di allarme antincendio' ]

['sistemi di allarme antincendio', 'incendio', 'ar']

In [10]:
if [k['id'] for k in kg.v(vertex='oasi').inc("synonym").all()['result']]:
    print('A')

In [11]:
for ref in find_nodes_by_language(kg, 'german'):
    print([k['id'] for k in kg.v(vertex=ref).inc("means").all()['result']])

['aménagements d enrichissement', 'impianti di ricarica', 'enrichment facilities', 'installations de recharge', 'sistemi di ricarica', 'recharge systems']
['rinforzamenti di ritorno', 'récupération d installations', 'raccoglitore di reflui', 'return facilities']
['registres-géologiques', 'registro del terreno', 'earth registers']
['piles-d énergie', 'impianti energetici', 'energy probes']
['perforations-de-sondage', 'perforazioni di sondaggio', 'sonde drillings']
['forages', 'fori di perforazione', 'drilling']
['classe d objet ponctuel', 'classe oggetto puntiforme', 'point object class']
['centrales électriques', 'kraftwerke centrali', 'hydroelectric power plants']
['mètre à pression', 'piezometro', 'piezometers']
['forage sondé', 'sonda di perforazione', 'exploration drilling']
['fontane per cani', 'fontaines de chasseur', 'fontane pubbliche', 'fountainheads']
['pozzi di pompaggio', 'puits à pompe', 'pozzi d acqua di pompaggio', 'wellheads']
['eau brute', 'acqua potabile', 'raw water']
['cours d eau', 'acque correnti', 'waters']
['qualité d eau', 'qualità dell acqua', 'water quality']
['numéro d itinéraire', 'numero di rotazione', 'route number']
['eaux fluviales', 'corso d acqua', 'streamwater']
['cours d eau permanent', 'corso d acqua', 'stream']
['point topologique', 'punto topologico', 'topology point']
['installations d étapes', 'strutture idriche', 'infrastructure']
['naturelité', 'natura autentica', 'naturalness']
['faisceaux-terrestres-arrières', 'strisce retrostanti', 'inland strip']
['eau-plat', 'acque basse', 'shallow water']
['sections-de-ligne-côtale', 'tratti di riva', 'lake shore sections']
['lacustre', 'vedute lagunari', 'lake shores']
['muséum naturel', 'musée naturel', 'museo naturale', 'natural museum']
['inventaire d amphibiens', 'inventario degli amfibi', 'amphibian inventory']
['données d état civil', 'dati anagrafici', 'vital statistics']
['office forestier', 'foresta', 'forest office']
['pleine-faîte', 'fatturazione di superficie forestale', 'area filling']
['waldfläche', 'forest area']
['unités sociales', 'unità sociali', 'society units']
['symbol building kit', 'boîte à symboles', 'costruzione simbolica', 'symbol box']
['principales catégories de processus', 'principali tipi di processo', 'main process types']
['types de procédure', 'tipi di processo', 'process types']
['processus principal', 'principale processo', 'main process']
['point d informations', 'punto d informazione', 'information point']
['événement naturel', 'natura evento', 'natural phenomenon']
['chute d édifice', 'collasso', 'collapse']
['chef-d affaires', 'principale', 'procédure principale', 'principale processo', 'main process type']
['caractéristiques du sujet', 'caratteristiche oggettuali', 'attributes']
['punktojbekte', 'puntogetti', 'pointed jackets']
['unités de terrain', 'unità territoriali', 'terrain units']
['profilures d images', 'profili acquisiti', 'profile recordings']
['espace vital', 'spazio vitale', 'living space']
['protection culturelle', 'protégeons-culturels', 'protégeons culturels', 'cultura protetta', 'cultural heritage protection']
['boisement', 'vegetazione arborea', 'shrub']
['arbre isolé', 'albero isolato', 'single tree']
['patrimonio geologico', 'geological feature', 'géotope', 'punto geologico', 'geological site']
['paysage géographique', 'paesaggio geologico', 'landscape']
['limites-de-stocks', 'limite di giacenza', 'stock limits']
['frontière-bois', 'waldgrenze', 'wald boundary']
['réglementations juridiques', 'norme legislative', 'règlements-juridiques', 'norme giuridiche', 'legal regulations']
['richesse créée', 'valore aggiunto', 'value creation']
['postes de travail', 'posti di lavoro', 'workplaces']
['détermination spatiale', 'definizione spaziale', 'spatial setting']
['plan d utilisation spéciale', 'sondernutzung - utilizzazione speciale', 'special use plan']
['terrain de golf', 'golfplatz - campo da golf', 'golf courses']
['transports publics', 'trasporto pubblico', 'public transportation']
['réserves d utilisation', 'riserve di utilizzo', 'reserve uses']
['zones ferroviaires', 'area della stazione', 'train station areas']
['système global du trafic', 'sistema di trasporto globale', 'total transportation system']
['aéronautique', 'aerotrasporto', 'air transport']
['sites d extraction', 'zone di estrazione', 'excavation sites']
['réserves d eau souterraines', 'riserve di acqua sotterranea', 'groundwater reserves']
['objectif de protection', 'obiettivo di protezione', 'protection goal']
['mesures de conservation', 'misure di gestione', 'conservation measures']
['communautés végétales et animales', 'comunità vegetali e animali', 'plant and animal communities']
['formes du relief', 'forme del terreno', 'landforms']
['fossiles et minéraux', 'componenti fossili e minerali', 'fossil and mineral contents']
['axe öv', 'asse del traffico pubblico', 'public transportation axis']
['transport en commun public', 'trasporto pubblico ferroviario', 'public long-distance transport']
['ligne st-gall-konstanz', 'san gallo-costanza', 'stgallen-konstanz']
['ligne st-margrethen-sargans', 'st margherita-sargans', 'stmargrethen-sargans']
['ligne zurich-st-gall-st-margrethen-munich', 'zürigo-stoccarda-ginevra-monaco', 'zurich-stgallen-stmargrethen-munich']
['grands projets de chemin de fer', 'grandi progetti ferroviari', 'major railway projects']
['lac de constance', 'lago di costanza', 'lake constance']
['lac zurich-obersee', 'lago zürich-obersee', 'zurich obersee']
['lac de walenstadt', 'lago di walenstadt', 'lake walen']
['industrie', 'attività economica', 'industry']
['protection du paysage culturel', 'tutela paesaggio culturale', 'cultural landscape protection']
['côte-du-lac', 'lake shores', 'rivage', 'riva del lago', 'seaside']
['valeurs angulaires', 'valori di angolo', 'key figures']
['travaux linéaires', 'lavoro ligneo', 'lintwork']
['arène tectonique', 'area di tectonica', 'tectonic arena']
['accord-programme', 'accordo programmatico', 'programme agreement']
['état contractant', 'stato contraente', 'contracting state']
['convention pour le patrimoine mondial', 'convenzione sul patrimonio mondiale', 'world heritage convention']
['sites culturels et naturels', 'siti di cultura e natura', 'cultural and natural landmarks']
['patrimoni dell umanità', 'unesco']
['patrimoines du monde', 'welterbegebiete', 'world heritage sites']
['espaces d expérience', 'spazi esperienziali', 'experience spaces']
['zones de protection du paysage', 'aree di protezione ambientale', 'landscape protection areas']
['biens naturels', 'beni naturali', 'natural assets']
['formes du terrain', 'forme del terreno', 'landforms']
['ressources fossiles et minérales', 'riserve fossili e minerali', 'fossil and mineral deposits']
['formations géologiques', 'formazioni geologiche', 'rock formations']
['zones d éclosion d amphibiens', 'zone di deposizione di anfibi', 'zones d amphibiens', 'zone umidicole di anfibi', 'amphibian breeding sites']
['impianti per uso e valorizzazione', 'utilization and enrichment facilities', 'installations d utilisation et d enrichissement', 'impianti per uso e miglioramento', 'utilization and enrichment installations']
['zones de protection du sous-sol', 'zone di protezione delle acque sotterranee', 'groundwater protection areas']
['risque de reflux dans le siphon', 'rischio di reflussione', 'backflow hazard']
['coûts d évacuation', 'costi di drenaggio', 'drainage costs']
['drainage urbain', 'drenaggio urbano', 'sewage system design']
['prairies naturelles', 'prati naturali', 'natural meadows']
['planification alimentaire', 'pianificazione alimentare', 'nutrition planning']
['base d alimentation régionale', 'base di approvvigionamento regionale', 'national supply basis']
['culture intensive', 'sequenza di raccolti', 'crop rotation']
['spéciales-règles', 'regolamentazioni speciali', 'special regulations']
['évêché territorial', 'decanato', 'territories']
['cure d âme', 'vicariato', 'soins spirituels', 'parrocchie', 'pastoral care', 'sécurité spirituelle', 'sacerdote', 'chancery']
['frontières-cantonnes', 'confine cantonale', 'canton border']
['saint-gallien', 'san gallo', 'saint gall']
['groupe de cantons', 'gruppo cantonale', 'canton group']
['échelon de généralisation', 'livello di generalizzazione', 'level of generalization']
['communautés primaires d éducation', 'comunità parrocchiali primarie', 'parish primary schools']
['communautés scolaires supérieures', 'comunità parrocchiali superiori', 'upper-level school communities']
['accords d inscription', 'accordi di ammissione all insegnamento primario', 'primary school accords', 'accords d inscription scolaire', 'accordi di ammissione all insegnamento superiore', 'enrollment agreements']
['contrats scolaires', 'accords scolaires', 'contratti scolastici', 'school agreements']
['communes scolaires', 'comuni scolastici', 'municipal schools', 'communautés scolaires', 'comunità scolastiche', 'school communities']
['écoles supérieures', 'istituti superiori', 'upper secondary schools']
['san gallo', 'saint gallen', 'st gallo', 'saint-gall', 'siena', 'st gallen']
['länder allemands', 'stati federati', 'federal states']
['linee di quote', 'linee d elevazione', 'linee di cima', 'lignes de crête', 'linee di elevazione', 'height lines']
['svizzero alt-3-d', 'suisse altis 3d', 'svizzero altitudine 3d', 'swiss alti 3d']
['plan du lin', 'linthplan']
['s-g 00072', 'sg00072']
['id-produit', 'identifiant produit', 'codice prodotto', 'id del prodotto', 'identifiant du produit', 'codice prodotto id', 'product-id', 'identifiant de produit', 'id prodotto', 'product id']
['vallée du rhin', 'valle del reno', 'rhine valley']
['date d expiration', 'data di consegna successiva', 'follow-up date']
['cartes topographiques', 'cartografia', 'topographic']
['carte du dufour', 'carta di du four', 'dufour map']
['échelle', 'scala', 'measurement standard']
['carte d expédition', 'carta di peso', 'scale card']
['images àériennes', 'immagini aerea colorate', 'aerial photographs', 'images aériennes à haute résolution', 'fotogrammi a colori', 'aerial images']
['fotografia ortometrica', 'ortho-photo', 'fotografia ortofonica', 'orthophtographie', 'fotografia ortofratta', 'orthophoto']
['immagine da satellite-mosaico', 'mosaïque d images satellites', 'immagine a mosaico da satellite', 'satellite image mosaic']
['mosaïque d image', 'mosaico d immagini', 'image mosaic']
['swissimage fcir', 'swissimage fci-r', 'swissimage fci raster images']
['infrarouge-orthophotomosaïque', 'infrarosso-ortofotomosaico', 'infrared orthophoto mosaic']
['visibilité mondiale', 'visibilità globale', 'global visibility']
['activités économiques', 'attività economiche', 'economic activities']
['agglomération', 'aggregato urbano', 'urban agglomeration']
['données schématiques', 'dati schemati', 'schematic data']
['pôles d activités', 'punti di attività', 'activity poles']
['aires urbaines', 'aree urbane', 'urban areas']
['modèle multimodal de transport', 'modello multimodale di trasporto', 'multi-modal transportation model']
['terrain à bâtir', 'terreno edificabile', 'building land']
['valeurs du terrain', 'valori del terreno', 'land values']
['catégories de valeur', 'categorie di valore', 'categories of value']
['conseil municipal', 'consiglio regionale', 'government council']
['traitement du marché', 'gestione del mercato', 'market development']
['heures d ouverture des magasins', 'orari di apertura dei negozi', 'store opening hours']
['corso d acqua', 'rapids routes', 'itinéraires-de-rafting', 'itinerari per rafting', 'rafting routes']
['activités nautiques', 'attività sportive acquatiche', 'water sports activities']
['restrictions temporelles', 'limitazioni temporali', 'temporal limitations']
['sections d eau', 'gli assunti idrici', 'cours d eau', 'gestioni di tratti d acqua', 'watercourse sections']
['activités nautiques', 'attività sportive acquatiche', 'water sports activities']
['réglementation maritime', 'normativa sulla navigazione fluviale', 'législation maritime', 'normativa sulla navigazione', 'shipping legislation']
['activités sportives', 'attività sportive', 'sports activities']
['sections de cours d eau', 'tratti d acqua', 'sections d eau', 'tratti di corso d acqua', 'sections of waterways']
['établissements d embarquement et de débarquement', 'parchi di accesso e uscita', 'entry and exit points', 'embarquements et débarquements', 'parchi degli ingressi e delle uscite', 'entrance and exit stations']
['terrains', 'proprietà fondiaria', 'plots of land']
['année fiscale', 'esercizio fiscale', 'tax year']
['district communal', 'distretto comunale', 'district council']
['règles du trafic', 'automobilisti', 'traffic regulations notes']
['plateau-seine-bienne', 'seeland-bielle/genève', 'seeland-biella/bienne', 'lake biel/bienne region']
['piani di bosco', 'piani forestali', 'plans forestiers', 'piani di foresta', 'forest plans']
['fonctions forestières', 'funzioni forestali', 'forest functions']
['production boisée', 'production bois', 'produzione di legno', 'wood production']
['répartition quantile', 'distribuzione quantile', 'quantile distribution']
['nuage de points', 'nuvola di punti', 'point cloud']
['stades de développement', 'fasi di sviluppo', 'development stages']
['information produit géographique', 'informazioni prodotti geografici', 'geo-product information']
['tableau de classification', 'tavola di classificazione', 'classification table']
['échelon d altitude', 'stadio d altitudine', 'elevation stage', 'étapes d altitude', 'stadio altimetrico', 'height stage']
['régions tarifaires', 'regioni tariffarie', 'tariff regions']
['percentuale di legno d albero', 'coniferous tree proportion', 'part du bois feuillus', 'percentuale di legno d alto fusto', 'needlewood proportion']
['composition principale et secondaire', 'composizione principale e secondaria', 'main and secondary stand']
['maximum height', 'hauteur supérieure', 'quota massima', 'upper canopy']
['images satellites', 'immagini satellitari', 'satellite images']
['modèle d altitude végétale', 'modèle d hauteurs végétales', 'modello di altezza vegetale', 'canopy height model', 'modèle d élévation végétale', 'vegetazioni-modelli di altitudine', 'vegetation height model']
['hectare de forêt', 'acri di foresta', 'hectares of forest']
['accès routier autorisé', 'accesso per autocarri', 'truck-accessible opening']
['plans de routes forestières', 'piani stradali forestali', 'forest road plans']
['plans d études', 'pianificazioni', 'plans']
['camions à charge', 'camioncisti', 'trucks']
['voies ferrées', 'piste merci', 'freight roads']
['transport forestier', 'trasporto legnami', 'timber transport']
['partage', 'parziale apertura', 'partial opening']
['zone boisée', 'area boscosa', 'forest area']
['circulation automobile', 'traffico veicolare stradale', 'motor vehicle traffic']
['stations-service', 'stazioni di servizio', 'gas stations']
['point d action', 'punto di misura', 'point of action']
['fournitures d énergie gazeuse', 'rifornimenti di gas', 'gas supplies']
['geo data set', 'ensemble géodatatique', 'scheda geodata', 'geo dataset']
['area di intervento', 'area of measures', 'massnahmengebiet', 'geospatial dataset area', 'zone d intervention', 'massimario-territorio', 'geospatial data set area']
['plan de projet', 'pianificazione del progetto', 'project plan']
['étapes de coordination', 'posizioni di coordinamento', 'coordination stages']
['système d eau léger pour les villes agréables', 'sistema di irrigazione e drenaggio delle acque (soelwa)', 'sewage']
['types de réseaux', 'tipologie di rete', 'network types']
['plans de fondation', 'pianificazioni', 'floor plans']
['installations voisines', 'installazioni ausiliarie', 'adjacent installations', 'installations annexes', 'installazioni accessorie', 'auxiliary installations']
['ouvrages spéciaux', 'opere speciali', 'special structures']
['barrage de stockage', 'opera di contenimento', 'storage structure']
['ouvrage d évacuation', 'opificio di scarico', 'overflow structure']
['pump station', 'centrale pompage', 'impianto idrico', 'pumpwork']
['tension élevée', 'alta tensione', 'high voltage']
['tension moyenne', 'tensione media', 'medium voltage']
['réseaux à haute tension', 'réseaux sous-marins', 'réseaux électriques', 'reti elettriche', 'networks']
['reti distributive', 'réseaux de distribution', 'reti di distribuzione', 'distribution networks']
['sous-tension', 'bassa tensione', 'low voltage']
['service des données', 'servizio dati', 'data service']
['point fixe', 'punto fisso', 'fixed point']
['punaise-numéro', 'punto numerico', 'coordinate number']
['coordonnées grossières', 'coordinata approssimativa', 'coarse coordinate']
['données mensuration offcielle', 'dati misurazione ufficiel', 'cadastral surveying data']
['adresse postale', 'postale', 'postal']
['numéro de plan', 'numero di piano', 'planning number']
['institutions culturelles', 'istituzioni culturali', 'cultural institutions']
['ruches', 'apiari', 'apiaries']
['lignées raciales', 'linee razziali', 'racial lines']
['nations d oiseaux', 'popoli d aeromobili', 'nations d oiseaux-volants', 'popolazioni d aeromobili', 'drone peoples']
['stations d abeilles', 'api stazioni', 'bee stations']
['arbres à haute tige', 'alberi a alto fusto', 'high-stem trees']
['fruits à noyau', 'frutta secca', 'stone fruits']
['cultures fruitières', 'colture commerciali', 'commercial fruit plantations']
['plantes brûlées au feu', 'piante infestanti da fuoco', 'fire-branded ornamental plants']
['perimètre de protection', 'schutzperimeter', 'security perimeter']
['responsable de l exploitation', 'gestore agricolo', 'manager']
['siège principal', 'edificio principale', 'main building']
['produktionsstätten', 'stabilimenti produttivi', 'sites de production', 'stabilimenti di produzione', 'production sites']
['sites d exploitation', 'sedi operative', 'operating locations']
['usine de production', 'impresa industriale', 'production site']
['organisme nuisible', 'organismo dannoso', 'organismal damage']
['unités d exploitation', 'unità di gestione', 'management units']
['racines tuberculeuses', 'cecolette radicate', 'root knobs']
['agriculture et horticulture', 'coltivazioni e orticoltura', 'farming and vegetable cultivation']
['herbe à mandarine', 'gramigna del mandorlo', 'earth almond grass']
['problèmes végétaux', 'problemi di coltivazione', 'problem plants']
['biens-fonds', 'proprietà fondiarie', 'land plots']
['plans-de-reseau-études', 'piani di rete-azione', 'networking plans']
['mesures-d ensemble', 'misurazioni-aree', 'areas for measures']
['périphérie du projet', 'perimetro del progetto', 'project perimeter']
['lac de bienne', 'lago di bienne', 'bienne lake']
['fond marin', 'fondovalle lacustre', 'lake ground']
['lake thunder', 'lac de thoune', 'lago di thoune', 'lake thun']
['profondeur d eau', 'profondità d acqua', 'water depth']
['informations sur les hauteurs', 'informazioni sulla quota', 'height information']
['batiments mensuration officielle', 'edifici misurazione ufficiale', 'aerial vehicle buildings']
['faussemes d enregistrements', 'lacune di registrazione', 'recording gaps']
['lacunes de données', 'lacune dati', 'data gaps']
['mètres carrés', 'metri quadrati', 'square meters']
['date du vol', 'data del volo', 'flight date']
['lignes aériennes', 'fluglinee', 'flight lines']
['itinéraires aériens', 'flugwegi', 'flight routes']
['télédétection à l aide d imagerie laser (lidar)', 'radar laser inérgique à distance active', 'radar a interferometria laser', 'imagerie à balayage laser', 'imagerie lidar', 'lidar', 'light detection and ranging', 'télédétection laser à balayage triangulaire (lidar)', 'rilevamento aereo con laser (lidar)', 'lidar (light detection and ranging)']
['modèle d affleurement', 'modello della superficie', 'modelli di superficie', 'modèle de surface', 'modello superficie', 'modèle d interface géographique', 'modello di superficie', 'surface model']
['hauteurs données', 'höhenangaben', 'elevation readings']

In [12]:
find_translation(kg, 'Brandmeldeanlagen', 'german')

['systèmes d alarme incendie',
 'sistemi di allarme antincendio',
 'fire alarm systems',
 'Brandmeldeanlagen']

In [ ]:
kg.v("carta dei pericoli").tag("from").out("means").tag("to").view("synonym").render()

#### Integrate hash for each term in the knowledge graph

In [55]:
language_dict = {'french':'fr', 'german':'de', 'italian':'it','english':'en'}
kg_terms, kg_hashes = [],[]
for lang in language_dict.keys():
    cols = ['title','name','abstract','keywords','keywords_nlp']
    cols.extend([col+'_'+language_dict[lang] for col in cols if col != 'name'])
    for term in tqdm(find_nodes_by_language(kg, lang)):
        mask = data[cols].apply(lambda c: c.astype(str).str.contains(term, case=False, na=False, regex=False)).any(axis=1)
        if not data[mask].empty:
            kg_hashes.append([h for h in data[mask].hash.to_list() if not '{' in h])
            kg_terms.append(term)
        # else:
        #     print(f"Nothing foud for {term}")

100%|██████████| 2562/2562 [10:00<00:00,  4.26it/s]
100%|██████████| 1935/1935 [07:44<00:00,  4.17it/s]
100%|██████████| 2685/2685 [09:53<00:00,  4.52it/s]
100%|██████████| 2304/2304 [07:51<00:00,  4.89it/s]

In [56]:
df = pd.DataFrame({'hashes':kg_hashes, 'term':kg_terms})

In [57]:
df.to_pickle('kg_hashes.pkl')

#### Load the knowledge graph with hashes

In [82]:
kg = generate_knowledge_graph(kg_name="GeoHarvester",kg_data_path='kg_data.pkl',
                              cog_home='knowledge_graph', load_hashes='kg_hashes.pkl',
                              load_synonyms=True)

KG system: Filtering translations...
KG system: Loading data in the knowledge graph...
0/5250
1/5250
2/5250
3/5250
4/5250
5/5250
6/5250
7/5250
8/5250
9/5250
10/5250
11/5250
12/5250
13/5250
14/5250
15/5250
16/5250
17/5250
18/5250
19/5250
20/5250
21/5250
22/5250
23/5250
24/5250
25/5250
26/5250
27/5250
28/5250
29/5250
30/5250
31/5250
32/5250
33/5250
34/5250
35/5250
36/5250
37/5250
38/5250
39/5250
40/5250
41/5250
42/5250
43/5250
44/5250
45/5250
46/5250
47/5250
48/5250
49/5250
50/5250
51/5250
52/5250
53/5250
54/5250
55/5250
56/5250
57/5250
58/5250
59/5250
60/5250
61/5250
62/5250
63/5250
64/5250
65/5250
66/5250
67/5250
68/5250
69/5250
70/5250
71/5250
72/5250
73/5250
74/5250
75/5250
76/5250
77/5250
78/5250
79/5250
80/5250
81/5250
82/5250
83/5250
84/5250
85/5250
86/5250
87/5250
88/5250
89/5250
90/5250
91/5250
92/5250
93/5250
94/5250
95/5250
96/5250
97/5250
98/5250
99/5250
100/5250
101/5250
102/5250
103/5250
104/5250
105/5250
106/5250
107/5250
108/5250
109/5250
110/5250
111/5250
112/5250
113/5250
114/5250
115/5250
116/5250
117/5250
118/5250
119/5250
120/5250
121/5250
122/5250
123/5250
124/5250
125/5250
126/5250
127/5250
128/5250
129/5250
130/5250
131/5250
132/5250
133/5250
134/5250
135/5250
136/5250
137/5250
138/5250
139/5250
140/5250
141/5250
142/5250
143/5250
144/5250
145/5250
146/5250
147/5250
148/5250
149/5250
150/5250
151/5250
152/5250
153/5250
154/5250
155/5250
156/5250
157/5250
158/5250
159/5250
160/5250
161/5250
162/5250
163/5250
164/5250
165/5250
166/5250
167/5250
168/5250
169/5250
170/5250
171/5250
172/5250
173/5250
174/5250
175/5250
176/5250
177/5250
178/5250
179/5250
180/5250
181/5250
182/5250
183/5250
184/5250
185/5250
186/5250
187/5250
188/5250
189/5250
190/5250
191/5250
192/5250
193/5250
194/5250
195/5250
196/5250
197/5250
198/5250
199/5250
200/5250
201/5250
202/5250
203/5250
204/5250
205/5250
206/5250
207/5250
208/5250
209/5250
210/5250
211/5250
212/5250
213/5250
214/5250
215/5250
216/5250
217/5250
218/5250
219/5250
220/5250
221/5250
222/5250
223/5250
224/5250
225/5250
226/5250
227/5250
228/5250
229/5250
230/5250
231/5250
232/5250
233/5250
234/5250
235/5250
236/5250
237/5250
238/5250
239/5250
240/5250
241/5250
242/5250
243/5250
244/5250
245/5250
246/5250
247/5250
248/5250
249/5250
250/5250
251/5250
252/5250
253/5250
254/5250
255/5250
256/5250
257/5250
258/5250
259/5250
260/5250
261/5250
262/5250
263/5250
264/5250
265/5250
266/5250
267/5250
268/5250
269/5250
270/5250
271/5250
272/5250
273/5250
274/5250
275/5250
276/5250
277/5250
278/5250
279/5250
280/5250
281/5250
282/5250
283/5250
284/5250
285/5250
286/5250
287/5250
288/5250
289/5250
290/5250
291/5250
292/5250
293/5250
294/5250
295/5250
296/5250
297/5250
298/5250
299/5250
300/5250
301/5250
302/5250
303/5250
304/5250
305/5250
306/5250
307/5250
308/5250
309/5250
310/5250
311/5250
312/5250
313/5250
314/5250
315/5250
316/5250
317/5250
318/5250
319/5250
320/5250
321/5250
322/5250
323/5250
324/5250
325/5250
326/5250
327/5250
328/5250
329/5250
330/5250
331/5250
332/5250
333/5250
334/5250
335/5250
336/5250
337/5250
338/5250
339/5250
340/5250
341/5250
342/5250
343/5250
344/5250
345/5250
346/5250
347/5250
348/5250
349/5250
350/5250
351/5250
352/5250
353/5250
354/5250
355/5250
356/5250
357/5250
358/5250
359/5250
360/5250
361/5250
362/5250
363/5250
364/5250
365/5250
366/5250
367/5250
368/5250
369/5250
370/5250
371/5250
372/5250
373/5250
374/5250
375/5250
376/5250
377/5250
378/5250
379/5250
380/5250
381/5250
382/5250
383/5250
384/5250
385/5250
386/5250
387/5250
388/5250
389/5250
390/5250
391/5250
392/5250
393/5250
394/5250
395/5250
396/5250
397/5250
398/5250
399/5250
400/5250
401/5250
402/5250
403/5250
404/5250
405/5250
406/5250
407/5250
408/5250
409/5250
410/5250
411/5250
412/5250
413/5250
414/5250
415/5250
416/5250
417/5250
418/5250
419/5250
420/5250
421/5250
422/5250
423/5250
424/5250
425/5250
426/5250
427/5250
428/5250
429/5250
430/5250
431/5250
432/5250
433/5250
434/5250
435/5250
436/5250
437/5250
438/5250
439/5250
440/5250
441/5250
442/5250
443/5250
444/5250
445/5250
446/5250
447/5250
448/5250
449/5250
450/5250
451/5250
452/5250
453/5250
454/5250
455/5250
456/5250
457/5250
458/5250
459/5250
460/5250
461/5250
462/5250
463/5250
464/5250
465/5250
466/5250
467/5250
468/5250
469/5250
470/5250
471/5250
472/5250
473/5250
474/5250
475/5250
476/5250
477/5250
478/5250
479/5250
480/5250
481/5250
482/5250
483/5250
484/5250
485/5250
486/5250
487/5250
488/5250
489/5250
490/5250
491/5250
492/5250
493/5250
494/5250
495/5250
496/5250
497/5250
498/5250
499/5250
500/5250
501/5250
502/5250
503/5250
504/5250
505/5250
506/5250
507/5250
508/5250
509/5250
510/5250
511/5250
512/5250
513/5250
514/5250
515/5250
516/5250
517/5250
518/5250
519/5250
520/5250
521/5250
522/5250
523/5250
524/5250
525/5250
526/5250
527/5250
528/5250
529/5250
530/5250
531/5250
532/5250
533/5250
534/5250
535/5250
536/5250
537/5250
538/5250
539/5250
540/5250
541/5250
542/5250
543/5250
544/5250
545/5250
546/5250
547/5250
548/5250
549/5250
550/5250
551/5250
552/5250
553/5250
554/5250
555/5250
556/5250
557/5250
558/5250
559/5250
560/5250
561/5250
562/5250
563/5250
564/5250
565/5250
566/5250
567/5250
568/5250
569/5250
570/5250
571/5250
572/5250
573/5250
574/5250
575/5250
576/5250
577/5250
578/5250
579/5250
580/5250
581/5250
582/5250
583/5250
584/5250
585/5250
586/5250
587/5250
588/5250
589/5250
590/5250
591/5250
592/5250
593/5250
594/5250
595/5250
596/5250
597/5250
598/5250
599/5250
600/5250
601/5250
602/5250
603/5250
604/5250
605/5250
606/5250
607/5250
608/5250
609/5250
610/5250
611/5250
612/5250
613/5250
614/5250
615/5250
616/5250
617/5250
618/5250
619/5250
620/5250
621/5250
622/5250
623/5250
624/5250
625/5250
626/5250
627/5250
628/5250
629/5250
630/5250
631/5250
632/5250
633/5250
634/5250
635/5250
636/5250
637/5250
638/5250
639/5250
640/5250
641/5250
642/5250
643/5250
644/5250
645/5250
646/5250
647/5250
648/5250
649/5250
650/5250
651/5250
652/5250
653/5250
654/5250
655/5250
656/5250
657/5250
658/5250
659/5250
660/5250
661/5250
662/5250
663/5250
664/5250
665/5250
666/5250
667/5250
668/5250
669/5250
670/5250
671/5250
672/5250
673/5250
674/5250
675/5250
676/5250
677/5250
678/5250
679/5250
680/5250
681/5250
682/5250
683/5250
684/5250
685/5250
686/5250
687/5250
688/5250
689/5250
690/5250
691/5250
692/5250
693/5250
694/5250
695/5250
696/5250
697/5250
698/5250
699/5250
700/5250
701/5250
702/5250
703/5250
704/5250
705/5250
706/5250
707/5250
708/5250
709/5250
710/5250
711/5250
712/5250
713/5250
714/5250
715/5250
716/5250
717/5250
718/5250
719/5250
720/5250
721/5250
722/5250
723/5250
724/5250
725/5250
726/5250
727/5250
728/5250
729/5250
730/5250
731/5250
732/5250
733/5250
734/5250
735/5250
736/5250
737/5250
738/5250
739/5250
740/5250
741/5250
742/5250
743/5250
744/5250
745/5250
746/5250
747/5250
748/5250
749/5250
750/5250
751/5250
752/5250
753/5250
754/5250
755/5250
756/5250
757/5250
758/5250
759/5250
760/5250
761/5250
762/5250
763/5250
764/5250
765/5250
766/5250
767/5250
768/5250
769/5250
770/5250
771/5250
772/5250
773/5250
774/5250
775/5250
776/5250
777/5250
778/5250
779/5250
780/5250
781/5250
782/5250
783/5250
784/5250
785/5250
786/5250
787/5250
788/5250
789/5250
790/5250
791/5250
792/5250
793/5250
794/5250
795/5250
796/5250
797/5250
798/5250
799/5250
800/5250
801/5250
802/5250
803/5250
804/5250
805/5250
806/5250
807/5250
808/5250
809/5250
810/5250
811/5250
812/5250
813/5250
814/5250
815/5250
816/5250
817/5250
818/5250
819/5250
820/5250
821/5250
822/5250
823/5250
824/5250
825/5250
826/5250
827/5250
828/5250
829/5250
830/5250
831/5250
832/5250
833/5250
834/5250
835/5250
836/5250
837/5250
838/5250
839/5250
840/5250
841/5250
842/5250
843/5250
844/5250
845/5250
846/5250
847/5250
848/5250
849/5250
850/5250
851/5250
852/5250
853/5250
854/5250
855/5250
856/5250
857/5250
858/5250
859/5250
860/5250
861/5250
862/5250
863/5250
864/5250
865/5250
866/5250
867/5250
868/5250
869/5250
870/5250
871/5250
872/5250
873/5250
874/5250
875/5250
876/5250
877/5250
878/5250
879/5250
880/5250
881/5250
882/5250
883/5250
884/5250
885/5250
886/5250
887/5250
888/5250
889/5250
890/5250
891/5250
892/5250
893/5250
894/5250
895/5250
896/5250
897/5250
898/5250
899/5250
900/5250
901/5250
902/5250
903/5250
904/5250
905/5250
906/5250
907/5250
908/5250
909/5250
910/5250
911/5250
912/5250
913/5250
914/5250
915/5250
916/5250
917/5250
918/5250
919/5250
920/5250
921/5250
922/5250
923/5250
924/5250
925/5250
926/5250
927/5250
928/5250
929/5250
930/5250
931/5250
932/5250
933/5250
934/5250
935/5250
936/5250
937/5250
938/5250
939/5250
940/5250
941/5250
942/5250
943/5250
944/5250
945/5250
946/5250
947/5250
948/5250
949/5250
950/5250
951/5250
952/5250
953/5250
954/5250
955/5250
956/5250
957/5250
958/5250
959/5250
960/5250
961/5250
962/5250
963/5250
964/5250
965/5250
966/5250
967/5250
968/5250
969/5250
970/5250
971/5250
972/5250
973/5250
974/5250
975/5250
976/5250
977/5250
978/5250
979/5250
980/5250
981/5250
982/5250
983/5250
984/5250
985/5250
986/5250
987/5250
988/5250
989/5250
990/5250
991/5250
992/5250
993/5250
994/5250
995/5250
996/5250
997/5250
998/5250
999/5250
1000/5250
1001/5250
1002/5250
1003/5250
1004/5250
1005/5250
1006/5250
1007/5250
1008/5250
1009/5250
1010/5250
1011/5250
1012/5250
1013/5250
1014/5250
1015/5250
1016/5250
1017/5250
1018/5250
1019/5250
1020/5250
1021/5250
1022/5250
1023/5250
1024/5250
1025/5250
1026/5250
1027/5250
1028/5250
1029/5250
1030/5250
1031/5250
1032/5250
1033/5250
1034/5250
1035/5250
1036/5250
1037/5250
1038/5250
1039/5250
1040/5250
1041/5250
1042/5250
1043/5250
1044/5250
1045/5250
1046/5250
1047/5250
1048/5250
1049/5250
1050/5250
1051/5250
1052/5250
1053/5250
1054/5250
1055/5250
1056/5250
1057/5250
1058/5250
1059/5250
1060/5250
1061/5250
1062/5250
1063/5250
1064/5250
1065/5250
1066/5250
1067/5250
1068/5250
1069/5250
1070/5250
1071/5250
1072/5250
1073/5250
1074/5250
1075/5250
1076/5250
1077/5250
1078/5250
1079/5250
1080/5250
1081/5250
1082/5250
1083/5250
1084/5250
1085/5250
1086/5250
1087/5250
1088/5250
1089/5250
1090/5250
1091/5250
1092/5250
1093/5250
1094/5250
1095/5250
1096/5250
1097/5250
1098/5250
1099/5250
1100/5250
1101/5250
1102/5250
1103/5250
1104/5250
1105/5250
1106/5250
1107/5250
1108/5250
1109/5250
1110/5250
1111/5250
1112/5250
1113/5250
1114/5250
1115/5250
1116/5250
1117/5250
1118/5250
1119/5250
1120/5250
1121/5250
1122/5250
1123/5250
1124/5250
1125/5250
1126/5250
1127/5250
1128/5250
1129/5250
1130/5250
1131/5250
1132/5250
1133/5250
1134/5250
1135/5250
1136/5250
1137/5250
1138/5250
1139/5250
1140/5250
1141/5250
1142/5250
1143/5250
1144/5250
1145/5250
1146/5250
1147/5250
1148/5250
1149/5250
1150/5250
1151/5250
1152/5250
1153/5250
1154/5250
1155/5250
1156/5250
1157/5250
1158/5250
1159/5250
1160/5250
1161/5250
1162/5250
1163/5250
1164/5250
1165/5250
1166/5250
1167/5250
1168/5250
1169/5250
1170/5250
1171/5250
1172/5250
1173/5250
1174/5250
1175/5250
1176/5250
1177/5250
1178/5250
1179/5250
1180/5250
1181/5250
1182/5250
1183/5250
1184/5250
1185/5250
1186/5250
1187/5250
1188/5250
1189/5250
1190/5250
1191/5250
1192/5250
1193/5250
1194/5250
1195/5250
1196/5250
1197/5250
1198/5250
1199/5250
1200/5250
1201/5250
1202/5250
1203/5250
1204/5250
1205/5250
1206/5250
1207/5250
1208/5250
1209/5250
1210/5250
1211/5250
1212/5250
1213/5250
1214/5250
1215/5250
1216/5250
1217/5250
1218/5250
1219/5250
1220/5250
1221/5250
1222/5250
1223/5250
1224/5250
1225/5250
1226/5250
1227/5250
1228/5250
1229/5250
1230/5250
1231/5250
1232/5250
1233/5250
1234/5250
1235/5250
1236/5250
1237/5250
1238/5250
1239/5250
1240/5250
1241/5250
1242/5250
1243/5250
1244/5250
1245/5250
1246/5250
1247/5250
1248/5250
1249/5250
1250/5250
1251/5250
1252/5250
1253/5250
1254/5250
1255/5250
1256/5250
1257/5250
1258/5250
1259/5250
1260/5250
1261/5250
1262/5250
1263/5250
1264/5250
1265/5250
1266/5250
1267/5250
1268/5250
1269/5250
1270/5250
1271/5250
1272/5250
1273/5250
1274/5250
1275/5250
1276/5250
1277/5250
1278/5250
1279/5250
1280/5250
1281/5250
1282/5250
1283/5250
1284/5250
1285/5250
1286/5250
1287/5250
1288/5250
1289/5250
1290/5250
1291/5250
1292/5250
1293/5250
1294/5250
1295/5250
1296/5250
1297/5250
1298/5250
1299/5250
1300/5250
1301/5250
1302/5250
1303/5250
1304/5250
1305/5250
1306/5250
1307/5250
1308/5250
1309/5250
1310/5250
1311/5250
1312/5250
1313/5250
1314/5250
1315/5250
1316/5250
1317/5250
1318/5250
1319/5250
1320/5250
1321/5250
1322/5250
1323/5250
1324/5250
1325/5250
1326/5250
1327/5250
1328/5250
1329/5250
1330/5250
1331/5250
1332/5250
1333/5250
1334/5250
1335/5250
1336/5250
1337/5250
1338/5250
1339/5250
1340/5250
1341/5250
1342/5250
1343/5250
1344/5250
1345/5250
1346/5250
1347/5250
1348/5250
1349/5250
1350/5250
1351/5250
1352/5250
1353/5250
1354/5250
1355/5250
1356/5250
1357/5250
1358/5250
1359/5250
1360/5250
1361/5250
1362/5250
1363/5250
1364/5250
1365/5250
1366/5250
1367/5250
1368/5250
1369/5250
1370/5250
1371/5250
1372/5250
1373/5250
1374/5250
1375/5250
1376/5250
1377/5250
1378/5250
1379/5250
1380/5250
1381/5250
1382/5250
1383/5250
1384/5250
1385/5250
1386/5250
1387/5250
1388/5250
1389/5250
1390/5250
1391/5250
1392/5250
1393/5250
1394/5250
1395/5250
1396/5250
1397/5250
1398/5250
1399/5250
1400/5250
1401/5250
1402/5250
1403/5250
1404/5250
1405/5250
1406/5250
1407/5250
1408/5250
1409/5250
1410/5250
1411/5250
1412/5250
1413/5250
1414/5250
1415/5250
1416/5250
1417/5250
1418/5250
1419/5250
1420/5250
1421/5250
1422/5250
1423/5250
1424/5250
1425/5250
1426/5250
1427/5250
1428/5250
1429/5250
1430/5250
1431/5250
1432/5250
1433/5250
1434/5250
1435/5250
1436/5250
1437/5250
1438/5250
1439/5250
1440/5250
1441/5250
1442/5250
1443/5250
1444/5250
1445/5250
1446/5250
1447/5250
1448/5250
1449/5250
1450/5250
1451/5250
1452/5250
1453/5250
1454/5250
1455/5250
1456/5250
1457/5250
1458/5250
1459/5250
1460/5250
1461/5250
1462/5250
1463/5250
1464/5250
1465/5250
1466/5250
1467/5250
1468/5250
1469/5250
1470/5250
1471/5250
1472/5250
1473/5250
1474/5250
1475/5250
1476/5250
1477/5250
1478/5250
1479/5250
1480/5250
1481/5250
1482/5250
1483/5250
1484/5250
1485/5250
1486/5250
1487/5250
1488/5250
1489/5250
1490/5250
1491/5250
1492/5250
1493/5250
1494/5250
1495/5250
1496/5250
1497/5250
1498/5250
1499/5250
1500/5250
1501/5250
1502/5250
1503/5250
1504/5250
1505/5250
1506/5250
1507/5250
1508/5250
1509/5250
1510/5250
1511/5250
1512/5250
1513/5250
1514/5250
1515/5250
1516/5250
1517/5250
1518/5250
1519/5250
1520/5250
1521/5250
1522/5250
1523/5250
1524/5250
1525/5250
1526/5250
1527/5250
1528/5250
1529/5250
1530/5250
1531/5250
1532/5250
1533/5250
1534/5250
1535/5250
1536/5250
1537/5250
1538/5250
1539/5250
1540/5250
1541/5250
1542/5250
1543/5250
1544/5250
1545/5250
1546/5250
1547/5250
1548/5250
1549/5250
1550/5250
1551/5250
1552/5250
1553/5250
1554/5250
1555/5250
1556/5250
1557/5250
1558/5250
1559/5250
1560/5250
1561/5250
1562/5250
1563/5250
1564/5250
1565/5250
1566/5250
1567/5250
1568/5250
1569/5250
1570/5250
1571/5250
1572/5250
1573/5250
1574/5250
1575/5250
1576/5250
1577/5250
1578/5250
1579/5250
1580/5250
1581/5250
1582/5250
1583/5250
1584/5250
1585/5250
1586/5250
1587/5250
1588/5250
1589/5250
1590/5250
1591/5250
1592/5250
1593/5250
1594/5250
1595/5250
1596/5250
1597/5250
1598/5250
1599/5250
1600/5250
1601/5250
1602/5250
1603/5250
1604/5250
1605/5250
1606/5250
1607/5250
1608/5250
1609/5250
1610/5250
1611/5250
1612/5250
1613/5250
1614/5250
1615/5250
1616/5250
1617/5250
1618/5250
1619/5250
1620/5250
1621/5250
1622/5250
1623/5250
1624/5250
1625/5250
1626/5250
1627/5250
1628/5250
1629/5250
1630/5250
1631/5250
1632/5250
1633/5250
1634/5250
1635/5250
1636/5250
1637/5250
1638/5250
1639/5250
1640/5250
1641/5250
1642/5250
1643/5250
1644/5250
1645/5250
1646/5250
1647/5250
1648/5250
1649/5250
1650/5250
1651/5250
1652/5250
1653/5250
1654/5250
1655/5250
1656/5250
1657/5250
1658/5250
1659/5250
1660/5250
1661/5250
1662/5250
1663/5250
1664/5250
1665/5250
1666/5250
1667/5250
1668/5250
1669/5250
1670/5250
1671/5250
1672/5250
1673/5250
1674/5250
1675/5250
1676/5250
1677/5250
1678/5250
1679/5250
1680/5250
1681/5250
1682/5250
1683/5250
1684/5250
1685/5250
1686/5250
1687/5250
1688/5250
1689/5250
1690/5250
1691/5250
1692/5250
1693/5250
1694/5250
1695/5250
1696/5250
1697/5250
1698/5250
1699/5250
1700/5250
1701/5250
1702/5250
1703/5250
1704/5250
1705/5250
1706/5250
1707/5250
1708/5250
1709/5250
1710/5250
1711/5250
1712/5250
1713/5250
1714/5250
1715/5250
1716/5250
1717/5250
1718/5250
1719/5250
1720/5250
1721/5250
1722/5250
1723/5250
1724/5250
1725/5250
1726/5250
1727/5250
1728/5250
1729/5250
1730/5250
1731/5250
1732/5250
1733/5250
1734/5250
1735/5250
1736/5250
1737/5250
1738/5250
1739/5250
1740/5250
1741/5250
1742/5250
1743/5250
1744/5250
1745/5250
1746/5250
1747/5250
1748/5250
1749/5250
1750/5250
1751/5250
1752/5250
1753/5250
1754/5250
1755/5250
1756/5250
1757/5250
1758/5250
1759/5250
1760/5250
1761/5250
1762/5250
1763/5250
1764/5250
1765/5250
1766/5250
1767/5250
1768/5250
1769/5250
1770/5250
1771/5250
1772/5250
1773/5250
1774/5250
1775/5250
1776/5250
1777/5250
1778/5250
1779/5250
1780/5250
1781/5250
1782/5250
1783/5250
1784/5250
1785/5250
1786/5250
1787/5250
1788/5250
1789/5250
1790/5250
1791/5250
1792/5250
1793/5250
1794/5250
1795/5250
1796/5250
1797/5250
1798/5250
1799/5250
1800/5250
1801/5250
1802/5250
1803/5250
1804/5250
1805/5250
1806/5250
1807/5250
1808/5250
1809/5250
1810/5250
1811/5250
1812/5250
1813/5250
1814/5250
1815/5250
1816/5250
1817/5250
1818/5250
1819/5250
1820/5250
1821/5250
1822/5250
1823/5250
1824/5250
1825/5250
1826/5250
1827/5250
1828/5250
1829/5250
1830/5250
1831/5250
1832/5250
1833/5250
1834/5250
1835/5250
1836/5250
1837/5250
1838/5250
1839/5250
1840/5250
1841/5250
1842/5250
1843/5250
1844/5250
1845/5250
1846/5250
1847/5250
1848/5250
1849/5250
1850/5250
1851/5250
1852/5250
1853/5250
1854/5250
1855/5250
1856/5250
1857/5250
1858/5250
1859/5250
1860/5250
1861/5250
1862/5250
1863/5250
1864/5250
1865/5250
1866/5250
1867/5250
1868/5250
1869/5250
1870/5250
1871/5250
1872/5250
1873/5250
1874/5250
1875/5250
1876/5250
1877/5250
1878/5250
1879/5250
1880/5250
1881/5250
1882/5250
1883/5250
1884/5250
1885/5250
1886/5250
1887/5250
1888/5250
1889/5250
1890/5250
1891/5250
1892/5250
1893/5250
1894/5250
1895/5250
1896/5250
1897/5250
1898/5250
1899/5250
1900/5250
1901/5250
1902/5250
1903/5250
1904/5250
1905/5250
1906/5250
1907/5250
1908/5250
1909/5250
1910/5250
1911/5250
1912/5250
1913/5250
1914/5250
1915/5250
1916/5250
1917/5250
1918/5250
1919/5250
1920/5250
1921/5250
1922/5250
1923/5250
1924/5250
1925/5250
1926/5250
1927/5250
1928/5250
1929/5250
1930/5250
1931/5250
1932/5250
1933/5250
1934/5250
1935/5250
1936/5250
1937/5250
1938/5250
1939/5250
1940/5250
1941/5250
1942/5250
1943/5250
1944/5250
1945/5250
1946/5250
1947/5250
1948/5250
1949/5250
1950/5250
1951/5250
1952/5250
1953/5250
1954/5250
1955/5250
1956/5250
1957/5250
1958/5250
1959/5250
1960/5250
1961/5250
1962/5250
1963/5250
1964/5250
1965/5250
1966/5250
1967/5250
1968/5250
1969/5250
1970/5250
1971/5250
1972/5250
1973/5250
1974/5250
1975/5250
1976/5250
1977/5250
1978/5250
1979/5250
1980/5250
1981/5250
1982/5250
1983/5250
1984/5250
1985/5250
1986/5250
1987/5250
1988/5250
1989/5250
1990/5250
1991/5250
1992/5250
1993/5250
1994/5250
1995/5250
1996/5250
1997/5250
1998/5250
1999/5250
2000/5250
2001/5250
2002/5250
2003/5250
2004/5250
2005/5250
2006/5250
2007/5250
2008/5250
2009/5250
2010/5250
2011/5250
2012/5250
2013/5250
2014/5250
2015/5250
2016/5250
2017/5250
2018/5250
2019/5250
2020/5250
2021/5250
2022/5250
2023/5250
2024/5250
2025/5250
2026/5250
2027/5250
2028/5250
2029/5250
2030/5250
2031/5250
2032/5250
2033/5250
2034/5250
2035/5250
2036/5250
2037/5250
2038/5250
2039/5250
2040/5250
2041/5250
2042/5250
2043/5250
2044/5250
2045/5250
2046/5250
2047/5250
2048/5250
2049/5250
2050/5250
2051/5250
2052/5250
2053/5250
2054/5250
2055/5250
2056/5250
2057/5250
2058/5250
2059/5250
2060/5250
2061/5250
2062/5250
2063/5250
2064/5250
2065/5250
2066/5250
2067/5250
2068/5250
2069/5250
2070/5250
2071/5250
2072/5250
2073/5250
2074/5250
2075/5250
2076/5250
2077/5250
2078/5250
2079/5250
2080/5250
2081/5250
2082/5250
2083/5250
2084/5250
2085/5250
2086/5250
2087/5250
2088/5250
2089/5250
2090/5250
2091/5250
2092/5250
2093/5250
2094/5250
2095/5250
2096/5250
2097/5250
2098/5250
2099/5250
2100/5250
2101/5250